export default {
  '/': 'Dashboard',
  '/schools': 'Сургууль',
  '/services': 'Үйлчилгээ',
  '/students': 'Сурагчид',
  '/students/create': 'Сурагч нэмэх',
  '/products': 'Бүтэгдэхүүн',
  '/products/create': 'Бүтэгдэхүүн Нэмэх',
  '/products/:id/edit': 'Бүтэгдэхүүн Засах',
  '/categories': 'Ангилал',
  '/categories/create': 'Ангилал Нэмэх',
  '/categories/:id/edit': 'Ангилал Засах',
  '/transactions/:id': 'Гүйлгээ дэлгэрэнгүй',
  '/transactions': 'Гүйлгээ',
  '/invoices': 'Нэхэмжлэл',
  '/invoices/create': 'Нэхэмжлэл үүсгэх',
  '/users': 'Хэрэглэгчид',
  '/profile': 'Хэрэглэгчийн мэдээлэл',
};
